<?php include 'php/header.php'; ?>
<script>$(document).ready(function(){ setTimeout(function (){$('#imageSlider').html('<ol class="carousel-indicators"><li data-target="#imageSlider" data-slide-to="0"></li><li data-target="#imageSlider" data-slide-to="1"></li><li data-target="#imageSlider" data-slide-to="2"></li><li data-target="#imageSlider" data-slide-to="3" class="active"></li></ol><div class="carousel-inner"><div class="item"><img alt="A picture from inside the classroom" src="img/slider/insideclass.jpg"><div class="carousel-caption"><h1>Inside Classroom</h1></div></div><div class="item"><img alt="A picture of the Team NSIT in South African Solar Challenge 2008 (World Rank - 3)" src="img/slider/solar.jpg"><div class="carousel-caption"><h1>Team NSIT in South African Solar Challenge 2008 (World Rank - 3)</h1></div></div><div class="item"><img alt="A picture of the Bullet Hawk Racing team" src="img/slider/bhr.jpg"><div class="carousel-caption"><h1>Bullet Hawk Racing</h1></div></div> <div class="active item"><img alt="A picture of central fountain" src="img/slider/centralfountain.jpg"><div class="unselectable carousel-caption"><h1>Central Fountain</h1></div></div></div><a class="left carousel-control" href="#imageSlider" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a><a class="right carousel-control" href="#imageSlider" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>');},750); });</script>

<div class="col-md-12">
  <div id="imageSlider" class="carousel slide">
  </div>
</div>
</div>
<div class="row">
<div id="content" class="col-md-offset-1 col-md-10">
  <p>Manufacturing Process and Automation Engineering (MPAE) is a uniquely hybrid field of engineering which amalgamates crucial aspects of mechanical, instrumentation and control engineering along with an introduction to computer science.  Often confused with mechanical, MPAE is the segment of engineering making it smarter. Techniques of manufacturing processes blended with IT makes it a branch with myriad useful applications. Apart from manufacturing, MPAE provides an exposure to robotics, process control along with it's economical aspects. Student's not only are equipped with technical know-how but also with the managerial and economical background of industries.</p>
  <p>Ever since its inception in 1947, automation has become a part and parcel of almost all medium and large scale industrial setups. Today,when the manufacturing economy is shifting from lean manufacturing to additive and agile manufacturing, automation plays a key role. A dexterous automation engineer requires a collective knowledge of the actual process as well as the tools required to automate it.  Thus the students of MPAE will have an edge over the students focusing on a particular engineering. Being so diversified in itself,it provides students a great scope to work in various fields like plant engineers, process engineers, quality engineers, operation analyst, management engineers, manufacturing engineers, quality control technicians etc. Students can pursue their masters in the area of manufacturing and automation as MPAE as a branch helps them locating their area of interest due to it's wide course structure.</p>
  <p>MPAE endeavour is to equip the student's undertaking the course to have immense knowledge about the mechanical world and making them tech savvy to meet the demands of future projects.</p>
</div>
<?php include 'php/footer.php'; ?> 